apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-deployment
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres-deployment
