apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-s3
  namespace: default
spec:
  selector:
    matchLabels:
      app: minio-s3
  template:
    metadata:
      labels:
        app: minio-s3
    spec:
      containers:
      - name: minio-s3
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        volumeMounts:
        - mountPath: /data
          name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
      volumes:
      - name: localvolume
        hostPath: # MinIO generally recommends using locally-attached volumes
          path: /mnt/disk1/data # Specify a path to a local drive or volume on the Kubernetes worker node
          type: DirectoryOrCreate # The path to the last directory must exist
